export const GET_CATEGORY = "GET_CATEGORY";
export const ERROR_CATEGORY = "ERROR_CATEGORY";
export const GET_CATEGORY_LIST = "GET_CATEGORY_LIST";
export const GET_PRODUCT = "GET_PRODUCT";
export const GET_CURRENCIES = "GET_CURRENCIES";
